openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  minLength: 3
                  maxLength: 60
                phone_number:
                  type: string
                  minLength: 10
                  maxLength: 13
                password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /login:
    post:
      summary: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  minLength: 10
                  maxLength: 13
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: sucess
        '401':
          description: Unauthorized
        '400':
          description: BadRequest
        '500':
          description: InternalServerError
  /profile:
    get:
      summary: get_user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
        '403':
          description: Unauthorized
        '500':
          description: InternalServerError
    put:
      summary: update_user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  minLength: 3
                  maxLength: 60
                phone_number:
                  type: string
                  minLength: 10
                  maxLength: 13
      responses:
        '200':
          description: Success
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
