services:
  app:
    build: .
    ports:
      - "8080:1323"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sawitpro?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sawitpro
    ports:
      - '5432:5432'
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
