// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/SawitProRecruitment/UserService/common/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddUserLoginCount mocks base method.
func (m *MockRepositoryInterface) AddUserLoginCount(ctx context.Context, in model.AddUserLoginCountReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserLoginCount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserLoginCount indicates an expected call of AddUserLoginCount.
func (mr *MockRepositoryInterfaceMockRecorder) AddUserLoginCount(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserLoginCount", reflect.TypeOf((*MockRepositoryInterface)(nil).AddUserLoginCount), ctx, in)
}

// GetUserByUserID mocks base method.
func (m *MockRepositoryInterface) GetUserByUserID(ctx context.Context, in model.GetUserByUserIDReq) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserID", ctx, in)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserID indicates an expected call of GetUserByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByUserID(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByUserID), ctx, in)
}

// GetUserPassword mocks base method.
func (m *MockRepositoryInterface) GetUserPassword(ctx context.Context, in model.GetUserPasswordReq) (model.GetUserPasswordRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPassword", ctx, in)
	ret0, _ := ret[0].(model.GetUserPasswordRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPassword indicates an expected call of GetUserPassword.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserPassword(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPassword", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserPassword), ctx, in)
}

// InsertUser mocks base method.
func (m *MockRepositoryInterface) InsertUser(ctx context.Context, in model.InsertUserReq) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, in)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockRepositoryInterfaceMockRecorder) InsertUser(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertUser), ctx, in)
}

// UpdateUserByUserID mocks base method.
func (m *MockRepositoryInterface) UpdateUserByUserID(ctx context.Context, in model.UpdateUserByUserIDReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByUserID", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByUserID indicates an expected call of UpdateUserByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateUserByUserID(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateUserByUserID), ctx, in)
}
